### ISSUE TITLE
Target temp not working

### ISSUE THREAD

**Issue by smucky06** [Snakey42069/homebridge-actronair#3]
**Describe The Bug:**
Target temperature doesnt appear to post to the unit

**To Reproduce:**
Set the device to Heat / Cool / Auto and adjust the target temp

**Expected behavior:**
Exected behaviour is that the target temp on the unit updates instead no change

**Logs:**

```
N/A
```

       
```json
     "accessories": [
                {
                    "name": "ActronConnect",
                    "ip": "10.1.1.163",
                    "mac": "########",
                    "device_token": "########",
                    "user_token": "##########",
                    "zones": [
                        {
                            "name": "Living",
                            "index": 0
                        },
                        {
                            "name": "Theatre",
                            "index": 1
                        },
                        {
                            "name": "Study",
                            "index": 2
                        },
                        {
                            "name": "Rumpus",
                            "index": 3
                        },
                        {
                            "name": "Bedrooms",
                            "index": 4
                        },
                        {
                            "name": "Masted Bed",
                            "index": 5
                        }
                    ]
                }
            ],
            "name": "Actron",
            "platform": "Homebridge Actronair"
```

**Screenshots:**
N/A

**Environment:**

* **Plugin Version**: v3.0.12
* **Homebridge Version**: v1.6.1
* **Node.js Version**: v18.13.0
* **NPM Version**: 8.19.3
* **Operating System**: Ubuntu Focal Fossa (20.04.5 LTS)

**Comment by ImpulsePurchase** [comment]
I think I am getting the same issue as this.  Other Changes such as setting the Mode or switching on/off Zones all works fine.  Only setting the Target Temp does not work.  

Endpoint 1: The [1.json](http://192.168.0.8/1.json) (or [identify.json)](http://192.168.0.8/identify.json)) endpoint returns:

{"device_Id":"AConnect","MacAddress":"XXXXXXXX","firmwareVersion":"V0.18G","capabilities":"proxy=true&softAP=true","BlockID":"ACONNECTXXXXXXXXX","NumEndpoints":6,"Endpoints":["Info","Network","WifiScan","Settings","ZoneSettings","Live"]}

Endpoint 2: The [2.json](http://192.168.0.8/2.json) endpoint returns:

{"ConnectionStatus":"111","CurrentConnection":{"SSID":"Large Hadron Collider","key":"XXXXXXXXXX","IP":"192.168.0.8","LinkStats":{**"errors":{"flags":"[5,9,C,M,N]","Count":30,"Last":"JsonErr->:\"setPoint\":23.5}**"},"stats":{"good":[74,7026],"bad":[0,0,0,2]}}},"PreferredConnection":{"SSID":"Large Hadron Collider","key":"35C0233B530F48580B8B7B81CD3D3AA53AD77952C3EB600BDEE5BB0B59FA274C","httpProxy":null},"RemoteServer":"que.actronair.com.au","ApiTo

Note the Last Error Reported is "setPoint\":23.5" highlighted by me in bold above.  This matches up with the last attempt to being a change to 23.5

**Comment by ImpulsePurchase** [comment]
I think I experience the same bug as this.  Setting other things such as setting the Mode to Auto or Cool works.  It only fails to set the Target Temp:

Debug log of a successful Mode change, followed by an attempt to change the target temp to 23.5, then 24, neither of which work, even though no error is shown in the log. The target temp stays as 22 degrees as reported in the log

07/06/2024, 1:42:42 pm] [Actron] ActronURL -> https://que.actronair.com.au/rest/v0/device/ACONNECTX?user_access_token=XX
[07/06/2024, 1:42:42 pm] [Actron] Data recieved from actron POST req -> {"result":1,"error":null,"id":0,"data":null}
[07/06/2024, 1:42:42 pm] [Actron] Aircon target state set to -> 1
[07/06/2024, 1:42:45 pm] [Actron] ActronURL -> https://que.actronair.com.au/rest/v0/device/ACONNECTX?user_access_token=0XX
[07/06/2024, 1:42:45 pm] [Actron] Data recieved from actron POST req -> {"result":1,"error":null,"id":0,"data":null}
[07/06/2024, 1:42:45 pm] [Actron] **Aircon setPoint set to -> 23.5**
[07/06/2024, 1:42:49 pm] [Actron] ActronURL -> https://que.actronair.com.au/rest/v0/device/ACONNECTX?user_access_token=XX
[07/06/2024, 1:42:49 pm] [Actron] Data recieved from actron POST req -> {"result":1,"error":null,"id":0,"data":null}
[07/06/2024, 1:42:49 pm] [Actron] **Aircon setPoint set to -> 24**
[07/06/2024, 1:43:05 pm] [Actron] Data recieved from actron GET req -> {
  isOn: true,
  mode: 1,
  fanSpeed: 2,
  **setPoint: 22,**
  roomTemp_oC: 21.9,
  isInESP_Mode: true,
  fanIsCont: 0,
  compressorActivity: 2,
  errorCode: '',
  individualZoneTemperatures_oC: [
      22,   22, 21.2,
    22.4, 22.2, 22.1,
    21.6,   22
  ],
  enabledZones: [
    1, 1, 0, 1,
    1, 1, 0, 0
  ],
  liveTimer: null
}

There is an error shown in the endpoint, notice JsonErr-> \"setPoint\":24} below,  this is reported after the unsuccessful attempt to set to 24 from above in the log

Endpoint 2: The [2.json](http://192.168.0.8/2.json) endpoint returns:
{"ConnectionStatus":"111","CurrentConnection":{"SSID":"SSSSS","key”:”xxxxxx”xxx,”IP":"192.168.0.8","LinkStats":{"errors":{"flags":"[5,9,C,M,N]","Count":32,"Last":"**JsonErr->:\"setPoint\":24}**"},"stats":{"good":[78,7133],"bad":[0,0,0,2]}}},"PreferredConnection":{"SSID":"Large Hadron Collider","key”:”xxxxxxxxxxx”,”httpProxy":null},"RemoteServer":"que.actronair.com.au","ApiToke

**Comment by ImpulsePurchase** [comment]
Forgot to give environment sets:

Plugin Version: v3.0.12
Homebridge Version: v1.8.2
Node.js Version: v20.14.0
NPM Version: 10.7.0
Operating System: macOS Monterey

**Comment by ImpulsePurchase** [comment]
I could be very wrong, but I suspect that instead of inside the function handleTargetTemperatureSet  where it sets the body of the PUT to : 
{ DA: { setPoint: value } }

Instead the payload may need to be in this format:

DA: 
{
    "amOn": true,
    "tempTarget": value,
    "fanSpeed": 2,
    "mode": 1
} 

where the values for amOn, fanSpeed and Mode are whatever the current settings are. And the requested temp value is assigned to "tempTarget" not "setPoint".  
I think that might be right because I see payloads like that via the Developer Tools on https://www.actronair.com.au/aconnect/#/Control

**Comment by tzarc** [comment]
I struck the same problem as @ImpulsePurchase -- the payload of the `PUT` is insufficient to change the temperature on mine. Quickly modifying the code to match the following payload results in temperature changes correctly functioning, at least on my system:
```js
DA: { [this.accessory.context.device.temp_key]: value, amOn: true, fanSpeed: 2, mode: 2 }
```

All other functions within 4.0.4 seem to work fine -- setting fan speed or enabling/disabling zones works perfectly.

**Comment by ImpulsePurchase** [comment]
Thanks for confirming that @tzarc !  Yes I still see the same behavior in 4.0.4 also.

I suspect there must be a some difference between systems as I'm assuming other user's don't have this problem.  In case this helps the system I am using is an:

  Actron Air ESP Ultima 3 Phase 20kW installed in 2017.  

  The ActronConnect module:
  1.  was installed along with it so is from 2017 also.
  2.  It's Serial Number starts  with: ACM-2 V0.17

**Comment by ImpulsePurchase** [comment]
Hold ON! Actually I've just re-tested again and it works after I re-touched the config.  I never remember there being a Temp_key parameter before.  I'm guessing I didn't have that set in my config correctly until I went back into the plugin config and re-saved.  I now have it saved as 'tempTarget' and re-started and it worked!

@tzarc do you have the config value Temp_key set to 'tempTarget'?    Now that I do setting the temp works, as does all the other features. 

EDIT: I've checked the backups of the JSON Config from before today and 
 "temp_key": "tempTarget",   
was missing until it was set today. All other values are the same.  So it appears the change done on Oct 18 2024 does fix the issue once you set temp_key to the right value. Which for an ESP Ultima is 'tempTarget"

**Comment by tzarc** [comment]
Indeed it was set to `tempTarget` -- enabling tracing with the `request` package showed the payloads and it was indeed sending the expected value.

Sending **just** `tempTarget` as per the current committed code does not result in a temperature setting change, sadly. The other fields are still necessary for it to be applied.

For clarity, mine's an _ESP Plus_ model, installed somewhere 2021-2022.

**Comment by ImpulsePurchase** [comment]
Ok @tzarc - I See what you are saying.  Probably makes sense for you to create a new issue for this.  That will get better visibility as no-one but us is probably looking here.  I've done a bit more testing on my system to ensure It wasn't just a one-off.  4.0.4 does appear to work for me reliably now.   And looking at the new code it does seem to simply substituting a variable that could be tempTarget or setPoint and sending a payload with either one of those and a value. 

So it looks like there are at least a few possible payload configurations for changing the desired temp:
1. Some work with just assigning a value to  setPoint
2. Some **can** work with just assigning a value to tempTarget (my example ESP Ultima 2017) but would also accept the payload version 3 below because that how the official app does it on my system.
3. Some work **only** when supplying:  amOn, tempTarget, fanSpeed, and Mode in the same request (your system ESP Plus 2021-2022)

**Comment by manningtelfer** [comment]
I've done some further investigation, and it looks as though there was a missunderstanding in my previous commit.

The **setPoint** parameter reflects the current temperature setpoint as reported by the Actron Connect system. The **tempTarget** parameter corresponds to the user-selected desired temperature—configured in the Actron Connect or Apple Home apps—which is then transmitted to the Actron Connect system to update the active setpoint.

I don't believe there are any systems that are using  **setPoint** in the put requests to update the user-selected desired temperature.

The temp_key setting could probably be removed, and the hard-coded tempTarget used in-place as it was previously.


@tzarc - Could you please include a sample of the payload being sent from Actron Connect when you change the temperature? You can access this by logging in via a web browser: https://www.actronair.com.au/aconnect/#/Control.
1. Open your browser dev tools, and nvigate to the network tab
2. Change the temperature so that it triggers new activity in the network tab
3. Look for the PUT request, click it and bring up the payload tab. It should look something like this (example from my system which is a **Standard Classic**): `{"DA":{"amOn":true,"tempTarget":22,"fanSpeed":0,"mode":2}}`

**Comment by Snakey42069** [comment]
Hi @manningtelfer @tzarc @ImpulsePurchase ,

Thanks for looking into this. 

Sadly, I don't own an Acton AC, I created this package as a favour for a friend. 

The only way I could test was by publishing new versions and having my friend update and restart in Homebridge (as evident by the unnecessarily long version history). 

I'm happy to assist where I can, however without an easy way to test I fear I may not be very useful. 

I can reach out to my friend for his model and PUT body / response. Let me know if that'll help. 

Thanks again for the contribution!

**Comment by ImpulsePurchase** [comment]
@manningtelfer I understand you were asking Nick (tzarc) directly in your message above, 

but just in case this helps when I follow your instructions I am getting from the PUT request, similar to as I reported back in June :

{"DA":{"amOn":true,"tempTarget":24.5,"fanSpeed":2,"mode":2}}

 where: the system is ON, temp asked for was 24.4, fans are currently in ESP setting, and Mode  is 'Cool'

response is "HTTP/1.1 200 OK" and checking via separate device connection to web app reveals desired temp successfully changed to 24.5

**Comment by manningtelfer** [comment]
Given that the Classic, and the ESP Ultima both work with the same payload, I suspect it should be working fine for the ESP Plus system as well. There may be another issue at play here with your system @tzarc. I would suggest you try reinstalling version 4.0.4 and reconfigure the plugin to see if that resolves the problem.

@Snakey42069 I'll submit a pull request to remove the **temp_key** setting as it's not actually needed.

**Comment by ImpulsePurchase** [comment]
where I suspect this set of four variables comes from is in the Script in the web app "Control.js" under the  SetTemperature function is does some logic to make sure the variable setPoint is a reasonable number between 16 and 30 where only x.0 or x.5 values are allowed. Then it calls SendConfiguration

```
// Do the change
      $scope.SendConfiguration();   
```
then  it creates this variable config:

```
      //For live mode
      var config = {
        amOn:         $scope.Power,
        tempTarget:   $scope.SetPoint,
        fanSpeed:     $scope.FanSpeed,
        mode:         $scope.ModeNumber
      };

      Airconditioner.SendConfiguration(config);
    };

```
And the rest of the code send those four values off presumably
EDIT: But it's calling this same SendConfiguration() code at the end of each kind of change you can do on this page, so there maybe no need to do it in this way, this could simply be an artifact of making this part of the code re-useable for all the four things you can control on this page of the app: ON/OFF, temp, fan speed and mode.
